### ISSUE TITLE
Maintain list of plugin repositories on Website

### ISSUE THREAD

**Issue by entropia1** [hannesrauhe/lunchinator-dev#1]
It would be nice if the external repositories were maintained on the main web site. And maybe a short tutorial on how to add one to the Lunchinator.

**Comment by hannesrauhe** [comment]
You're right.

Btw: https://github.com/hannesrauhe/lunchinator/issues/157 ;-)

**Comment by hannesrauhe** [comment]
Well, it took a while:
www.lunchinator.de/#plugins
